### ISSUE TITLE
Confirm month names are correct

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#1]
I just used Google translate so it would be good to could check these with Yuri:

https://github.com/openaustralia/ukraine_verkhovna_rada_deputies/blob/master/scraper.rb#L18-L47

**Comment by beastie87** [comment]
I check def ukrainian_month_to_i, it is good)))

**Comment by lisoffsky** [comment]
there is mistake in word endings, I think. below you can find the list.
when "січень"
    1
  when "лютий"
    2
  when "березень"
    3
  when "квітень"
    4
  when "травень"
    5
  when "червень"
    6
  when "липень"
    7
  when "серпень"
    8
  when "вересень"
    9
  when "жовтень"
    10
  when "листопад"
    11
  when "грудень"
    12

**Comment by beastie87** [comment]
If the date will be taken with this type of term 
ДАТА НАБУТТЯ ДЕПУТАТСЬКИХ ПОВНОВАЖЕНЬ:
27 листопада 2014р.
ДАТА ПРИПИНЕННЯ ДЕПУТАТСЬКИХ ПОВНОВАЖЕНЬ:
2 грудня 2014р.

@henare  option is true

**Comment by henare** [comment]
Thanks @beastie87 and @lisoffsky. The dates we're parsing are on pages like this: http://itd.rada.gov.ua/mps/info/page/15650

So from what I understand from your conversation is that this is working correctly and the names match that format. Please reopen this issue if I misunderstood.
