### ISSUE TITLE
Check split names are correct

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#10]
In #9 we split the names up we just need to check they're correct.

**Comment by beastie87** [comment]
Yes, split name is correct)
more detail: 
full name ->  last name  first name  middle name
  name short ->  last name  first name[0].  middle name[0].
Eg:
 I am Kondratenko Gennadij Sergiyovych
 Мое прізвище ім’я по батькові
 Кондратенко Геннадій Сергійович
 name short:  Kondratenko G.S.
 Скорочена форма запису ПІБ: Кондратенко Г.С.
 if eg
surname = "Кондратенко" #last name
first_name ="Геннадій"    #first name
middle_name ="Сергійович" #middle name

nameshort = "#{surname} #{first_name[0]}.#{middle_name[0]}." 
puts nameshort #=> "Кондратенко Г.С."

**Comment by henare** [comment]
Perfect, thanks @beastie87 - that's really helpful :star: 

I'll close this as done for the moment.
