### ISSUE TITLE
MPs names issue

### ISSUE THREAD

**Issue by lisoffsky** [openaustralia/ukraine_verkhovna_rada_deputies#17]
For now in MPs profiles are published patronymics and surnames and there is no first name.

**Comment by henare** [comment]
Oops, thanks @lisoffsky - that's a big issue! :)

More info: https://github.com/OPORA/publicwhip/issues/19

**Comment by henare** [comment]
According to @mmitre on OPORA/publicwhip#19 we need to swap the `given_name` and `middle_name` field.

**Comment by henare** [comment]
@lisoffsky or @mmitre Before I go ahead and make this change, can you please confirm that I need to swap the `given_name` and `middle_name` field?

**Comment by henare** [comment]
Reading @beastie87's comment here it seems we do need to make this change: https://github.com/openaustralia/ukraine_verkhovna_rada_deputies/issues/10#issuecomment-138993184

**Comment by mmitre** [comment]
Correct. Looking at the site right now, it seems that given_name and middle_name still need to be swapped. Thanks.

**Comment by henare** [comment]
Thanks @mmitre :+1:
