### ISSUE TITLE
2 pages for 1 MP

### ISSUE THREAD

**Issue by lisoffsky** [openaustralia/ukraine_verkhovna_rada_deputies#20]
For now we found two duplicates
first
https://tvfy-ukraine.oaf.org.au/search?query=%D0%B7%D1%83%D0%B1%D0%B0%D1%87&button=hero_search

and second
https://tvfy-ukraine.oaf.org.au/search?query=%D0%B1%D0%B0%D1%82%D0%B5%D0%BD%D0%BA%D0%BE&button=Search

looks like this is because of faction jumpings

**Comment by henare** [comment]
Moved to https://github.com/OPORA/publicwhip/issues/140
