### ISSUE TITLE
Add webhook to scraper?

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/ukraine_verkhovna_rada_deputies#24]
As we're using this scraper to feed EveryPolitician, it would be super-useful if you could set a webhook of `https://everypolitician-rebuilder.herokuapp.com/rebuild/Ukraine/Verkhovna-Rada/official` to auto-trigger a rebuild if anything has changed…

**Comment by henare** [comment]
Too easy @tmtmtmtm, done :+1:

**Comment by tmtmtmtm** [comment]
Thanks @henare!
