### ISSUE TITLE
Is there some way of tracking faction changes?

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#3]
Ideally we'd have a list of deputies' previous faction memberships, with start and end dates.

**Comment by lisoffsky** [comment]
Each MP page has button "Переходи по фракціях". When open it, there will be a list of his faction jumps and from here you can track faction membership of each MP. e.g. http://w1.c1.rada.gov.ua/pls/site2/p_deputat_fr_changes?d_id=5549

**Comment by henare** [comment]
@lisoffsky perfect! I've opened #11 to track adding this data to the scraper.
