### ISSUE TITLE
What should "Multi County" deputies have their "area" set to?

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#5]
For the electorate/constituency/area for some deputies we're currently getting a field that translates to either "Multi County".

This doesn't seem very helpful - what should it be set to, if anything?

My guess is that these people are party list MPs and so we shouldn't set an area.

**Comment by beastie87** [comment]
The some deputies we're currently getting a field Multi County on Ukrainian language -  Загальнодержавному багатомандатному округу?

**Comment by beastie87** [comment]
Загальнодержавному багатомандатному округу  - It was elected by all regions of Ukraine, else 
getting a field elected by according to district.

**Comment by lisoffsky** [comment]
that means they were elected by party lists.
our electoral system is parallel. Half of Parliament we elect in 225 single mandate districts and another half by voting for parties lists.

**Comment by lisoffsky** [comment]
that means they were elected by party lists.
our electoral system is parallel. Half of Parliament we elect in 225 single
mandate districts and another half by voting for parties lists.

On Wed, Sep 9, 2015 at 9:26 PM, beastie87 notifications@github.com wrote:

> Загальнодержавному багатомандатному округу - It was elected by all regions
> of Ukraine, else
> getting a field according to district.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openaustralia/ukraine_verkhovna_rada_deputies/issues/5#issuecomment-138998505
> .

## 

Iurii Lisovskyi
tel/fax: +38 044 286 2670

**Comment by mmitre** [comment]
Technically, they belong to a national constituency, so we could mark as such.

**Comment by henare** [comment]
We seem to be pretty happy with

> Загальнодержавному багатомандатному округу

so I'll close this.
