### ISSUE TITLE
For deputies with a constituency should we set their "area" to a location?

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#6]
For the electorate/constituency/area of deputies with a constituency we're currently getting a field that translates to something like "Constituency №222".

But Google Translate tells me there's also a location field so should we use that instead?

e.g. http://itd.rada.gov.ua/mps/info/page/15839 has "РЕГІОН: м. Київ" - should we set `area` to "м. Київ" instead of the current "Виборчому округу №222"?

**Comment by tmtmtmtm** [comment]
The ideal solution would be to map them to OCD Divisions, though at the minute it seems those are only defined for the regions of Ukraine (https://github.com/opencivicdata/ocd-division-ids/blob/master/identifiers/country-ua.csv) rather than constituencies.

**Comment by tmtmtmtm** [comment]
The Wikipedia members table has both values, btw:
https://uk.wikipedia.org/wiki/Верховна_Рада_України_VII_скликання

**Comment by henare** [comment]
Great, thanks @tmtmtmtm! That does sound like the way to go.

I'll wait to hear what @jnlandry and Yuri on the ground there say.

**Comment by beastie87** [comment]
The big city or large cities (eg Kyiv) have areas "location".
The area is a Constituency  or 2 constituencies,  depends on the number of polling stations
http://www.cvk.gov.ua/pls/vnd2012/WP023?PT001F01=900&PID100=80 - this link you will see constituencies Kyiv.
As constituency elect their MP, so you need to show speed by which constituency he was elected

**Comment by mmitre** [comment]
At its lowest level, a district can cover a portion of a city, or multiple villages together. My inclination would be to say something like "District XX, YY Oblast" (or, in the case of Kyiv City and Sevastopol, "District XXX, YYY City". That way, you get at least some idea of where in the country people come from, but don't have to deal with the actual district boundaries. It would be the equivalent of saying that a House member in the US is from California's 3rd district. @lisoffsky, would you agree?

**Comment by lisoffsky** [comment]
@mmitre, thank you, that's a good idea
