### ISSUE TITLE
Are the parties we're scraping correct?

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#7]
We're currently scraping 7 unique parties:
- політична партія Всеукраїнське об'єднання "Батьківщина"
- ПАРТІЯ "БЛОК ПЕТРА ПОРОШЕНКА"
- Політична партія "НАРОДНИЙ ФРОНТ"
- Радикальна Партія Олега Ляшка
- [none]
- Політична партія "Об'єднання "САМОПОМІЧ"
- Політична партія "Опозиційний блок"

They Google translate to:
- political party All-Ukrainian Union "Fatherland"
- PARTY "Petro Poroshenko Bloc"
- Political party "People's Front"
- Radical Party Oleg Lyashko
- [none]
- Political party "Union" Self "
- Political party "opposition bloc"

There's lots of "Political party 'Some party'". Should we be cleaning this data up at all? If so, how?

This is how you can easily get a CSV of all the parties:

https://api.morph.io/openaustralia/ukraine_verkhovna_rada_deputies/data.json?query=select%20DISTINCT%28%60party%60%29%20from%20%27data%27&key=[YOUR_MORPH_KEY]

**Comment by beastie87** [comment]
It is very good! 
I think that we should change
family_name  - >  last name or surname
middle_name - >  first name
given_name  ->  middle name

And I think this should be a type link http://itd.rada.gov.ua/mps/info/page/2524
 scraping with:
Голосування депутата
Реєстрація депутата за допомогою електронної системи
Письмова реєстрація депутата
Переходи по фракціях
Посади протягом скликання
Хронологія виступів депутата
Депутатські запити
Законотворча діяльність
Декларації про доходи
for next scraping data

**Comment by mmitre** [comment]
Question is trickier than it appears.

In terms of whether the strings are being scraped correctly from http://w1.c1.rada.gov.ua/pls/site2/p_fraction?pidid=2613, the answer is yes. My inclination would be to leave as is (e.g. official, long names), but @lisoffsky can confirm. My only suggested change in this regard is to use only initial capital letters for those strings that are all capitals.

The question is how we're using this info. Looking at the Rada website, it seems that this information is only available for party list MPs (e.g. Jane Doe was elected in the national district under the Red Party list). However, to get information on which party nominated a single-mandate MP, you need to look at "суб’єкт висування" under the section "на момент обрання". E.g. for http://itd.rada.gov.ua/mps/info/page/18127, it would be Політична партія "Об’єднання "САМОПОМІЧ". MPs who ran as independents would have "самовисування" under на момент обрання.

@lisoffsky, makes sense?

**Comment by lisoffsky** [comment]
yes @mmitre, thank you.
and @henare please change Political party "Union" Self "  to Political party "Samopomich". Its to have it transliterated, not translated, I think

**Comment by mmitre** [comment]
@lisoffsky's comment brings up a good point. Are we including in the database both English and Ukrainian? If so, for party names, the translation/transliteration might want to be done by hand and/or checked by someone in Ukraine. For people's names, we can just transliterate from Ukrainian to English characters. I believe there is an official transliteration table, but it's pretty close to the BGN/PCGN column at https://en.wikipedia.org/wiki/Romanization_of_Ukrainian. 

If we're only storing the Ukrainian, then this of course is a non-issue.

**Comment by henare** [comment]
> If we're only storing the Ukrainian, then this of course is a non-issue.

Yes, this is a very good point. I should have been clearer from the start. We're only storing the Ukrainian because that's what we'll be using on the site eventually.

I've been Google Translating as I test to see if they make sense :)

**Comment by henare** [comment]
I think we can close this as done for the moment. Please reopen if you disagree.
