### ISSUE TITLE
Are the factions we're scraping correct?

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_deputies#8]
Similar question to #7 but for the factions.

What we're getting:
- Член депутатської фракції політичної партії "Всеукраїнське об'єднання "Батьківщина" у Верховній Раді України
- Член депутатської фракції ПАРТІЇ "БЛОК ПЕТРА ПОРОШЕНКА"
- Член депутатської фракції Політичної партії "НАРОДНИЙ ФРОНТ"
- Член депутатської фракції Радикальної партії Олега Ляшка
- Не входить до складу будь-якої фракції
- Член депутатської фракції Політичної партії "Об'єднання "САМОПОМІЧ"
- Член депутатської фракції Політичної партії "Опозиційний блок" у Верховній Раді України восьмого скликання
- Член депутатської групи "Воля народу"
- Член депутатської групи "Партія "Відродження"
- Заступник голови депутатської фракції Політичної партії "НАРОДНИЙ ФРОНТ"
- Голова депутатської фракції Політичної партії "Об'єднання "САМОПОМІЧ"
- Голова депутатської фракції Політичної партії "Опозиційний блок" у Верховній Раді України восьмого скликання
- Співголова депутатської групи групи "Партія "Відродження"
- Голова депутатської фракції Політичної партії "НАРОДНИЙ ФРОНТ"
- Заступник голови депутатської фракції Політичної партії "Опозиційний блок" у Верховній Раді України восьмого скликання
- Заступник голови депутатської фракції ПАРТІЇ "БЛОК ПЕТРА ПОРОШЕНКА"
- [none]
- Заступник голови депутатської групи "Воля народу"
- Голова депутатської групи "Воля народу"
- Перший заступник Голови депутатської фракції ПАРТІЇ "БЛОК ПЕТРА ПОРОШЕНКА"
- Заступник голови депутатської фракції Політичної партії "Об'єднання "САМОПОМІЧ"
- Заступник голови депутатської фракції Радикальної партії Олега Ляшка
- Голова депутатської фракції ПАРТІЇ "БЛОК ПЕТРА ПОРОШЕНКА"
- Голова депутатської фракції Радикальної партії Олега Ляшка
- Заступник голови депутатської фракції політичної партії "Всеукраїнське об'єднання "Батьківщина" у Верховній Раді України
- Перший заступник Голови депутатської фракції Політичної партії "НАРОДНИЙ ФРОНТ"
- Голова депутатської фракції політичної партії "Всеукраїнське об'єднання "Батьківщина" у Верховній Раді України

Translated:
- A member of the parliamentary faction of the party "All-Ukrainian Union" Fatherland "in the Verkhovna Rada of Ukraine
- A member of the parliamentary faction of the Party "Petro Poroshenko Bloc"
- A member of the parliamentary faction of political party "People's Front"
- Member of the Radical Party parliamentary faction Oleg Lyashko
- Not part of any faction
- A member of the parliamentary faction of political party "Union" Self "
- A member of the parliamentary faction of political party "Opposition Bloc" in the Verkhovna Rada of Ukraine of the eighth convocation
- Member of the parliamentary group "will of the people"
- A member of the group "Party" Renaissance "
- Deputy Chairman of the parliamentary faction of political party "People's Front"
- Head of the parliamentary faction of political party "Union" Self "
- Head of the parliamentary faction of political party "Opposition Bloc" in the Verkhovna Rada of Ukraine of the eighth convocation
- Co-Chairman of the parliamentary group of the "Party" Renaissance "
- Head of the parliamentary faction of political party "People's Front"
- Deputy Chairman of the parliamentary faction of political party "Opposition Bloc" in the Verkhovna Rada of Ukraine of the eighth convocation
- Deputy Chairman of the parliamentary faction of the Party "Petro Poroshenko Bloc"
  *
- Deputy Chairman of the parliamentary group "will of the people"
- Head of the deputy group "will of the people"
- First Deputy Chairman of the parliamentary faction of the Party "Petro Poroshenko Bloc"
- Deputy Chairman of the parliamentary faction of political party "Union" Self "
- Deputy Chairman of the parliamentary faction of the Radical Party Oleg Lyashko
- Head of the parliamentary faction of the Party "Petro Poroshenko Bloc"
- Head Radical Party parliamentary faction Oleg Lyashko
- Deputy Chairman of the parliamentary faction of the party "All-Ukrainian Union" Fatherland "in the Verkhovna Rada of Ukraine
- First Deputy Chairman of the parliamentary faction of political party "People's Front"
- Head of the parliamentary faction of the party "All-Ukrainian Union" Fatherland "in the Verkhovna Rada of Ukraine

**Comment by tmtmtmtm** [comment]
For EveryPolitician, at least, although presumably also for what you're doing, you'll need to squash all those "Chairman of Faction X", "Deputy-head of Faction X", together with just the plain Faction X. At the moment our process doesn't include an easy way to capture and expose those sorts of roles on the Faction itself. Adding it shouldn't be _too_ difficult, but it's definitely non-trivial, so I'd prefer not to do it just yet unless it's something you're actually going to need. If you think you'll want them at some point, then I'd suggest storing it in a separate 'faction_role' column or the like, which we can ignore for now, and work out how to deal with later.

**Comment by henare** [comment]
@tmtmtmtm great point, thanks! I think we're only interested in the faction for the moment too but your suggested solution if we do need them sounds like just the ticket.

I'm hoping our Ukrainian partners can advise all the correct factions we should be seeing so we can map them correctly.

**Comment by tmtmtmtm** [comment]
Good plan. You can see what the current data looks like, btw, at https://everypolitician-viewer-pr-609.herokuapp.com/ukraine/verkhovna-rada/term-table/8.html

**Comment by henare** [comment]
That's awesome :)

**Comment by tmtmtmtm** [comment]
@henare — consolidating the factions looks like the biggest blockage to a minimal acceptable version for EveryPolitician (we'd obviously like much more, but it's OK for that to improve over time). Do you think there's any likelihood of that happening this week during our [GLOW push](https://www.mysociety.org/2015/09/07/how-quickly-can-we-get-to-200-countries-on-every-politician/)?

**Comment by mmitre** [comment]
The Rada website has a page per faction (e.g. http://w1.c1.rada.gov.ua/pls/site2/p_fraction_list?pidid=2613) with all the faction members.

The page with the faction names (and the link to the page listing the faction members can be found at http://w1.c1.rada.gov.ua/pls/site2/p_fractions. From there, clicking on a faction name will take you to a faction page (e.g. for the Poroshenko Bloc, it goes to http://w1.c1.rada.gov.ua/pls/site2/p_fraction?pidid=2613). From there, click on the "Faction" link and it will take you to the list of members.

Note that technically, factions are related to political parties, while groups are MPs coming together but no linked to any party. For the DB, this shouldn't matter, but wanted to give context since the page includes both factions and groups. Both are equivalent and should be included in the DB.

**Comment by henare** [comment]
> Do you think there's any likelihood of that happening this week during our GLOW push?

@tmtmtmtm Yes, we're very keen to do that. We had a bit of a hold up the last few days but I'm back on this full time now.

> Note that technically, factions are related to political parties, while groups are MPs coming together but no linked to any party. For the DB, this shouldn't matter, but wanted to give context since the page includes both factions and groups. Both are equivalent and should be included in the DB.

This is excellent, thanks @mmitre! I'll use those lists to set the factions in this database.

**Comment by henare** [comment]
@tmtmtmtm this has been fixed in e728b01. I'm going to be away from the internet for the weekend so I don't have time to finish off my EP PR right now but I'll get back to it next week.

**Comment by tmtmtmtm** [comment]
Thanks @henare — I'm happy enough to do the integration into EP myself today.

**Comment by tmtmtmtm** [comment]
Now live: http://everypolitician.org/ukraine/

Thanks for taking them time to do this all in an EP-compatible way @henare

**Comment by henare** [comment]
Thanks @tmtmtmtm! :dancers:
